Add count for if not number
HDCodePractice/CodePracticeBot pull request #2
Opened 2020-10-03 14:50 UTC by Sichengthebest

2020-10-04 04:07 UTC, hdcola requested changes

2020-10-04 04:07 UTC, hdcola commented on cmdproc/guesscmd.py
> +        tcount += 1
这里如果对tcount加一没用啊，因为之后就直接return了

2020-10-04 14:43 UTC, Sichengthebest commented on cmdproc/guesscmd.py
> +        tcount += 1
?

2020-10-04 15:34 UTC, hdcola commented on cmdproc/guesscmd.py
> +        tcount += 1
你仔细看看，如果要加，需要改的不止这一点呢

2020-10-06 18:15 UTC, hdcola commented
guess已经大变身，这个已经不用再考虑修改了

2020-10-06 18:15 UTC, closed without merging